# frozen_string_literal: true

source "https://rubygems.org"

gem 'capybara', '3.33'
gem 'cucumber', '5.2'
gem 'selenium-webdriver', '~> 3.142', '>= 3.142.7'
gem 'rspec', '3.10'
gem 'faker', '2.14'
gem 'mongo', '2.13.1'