
require "digest/md5"

require_relative "features/support/libs/mongo"

def to_md5(pass)
  return Digest::MD5.hexdigest(pass)
end

task :test do
    puts "Executando uma tarefa de teste"
end

task :local_seeds do

    CONFIG = YAML.load_file(File.join(Dir.pwd, "features/support/config/local.yml"))

    users = [
        { name: "Virtrus", email: "virtrudes@cats.com", password: to_md5("pwd123") },
        { name: "Venus", email: "venus@cats.com", password: to_md5("pwd123") },
        { name: "Anderson Silva", email: "spider@email.com", password: to_md5("pwd123") },
        { name: "Extra", email: "extraT@email.com", password: to_md5("pwd123") },
        { name: "Joao", email: "joao@anunciante.com", password: to_md5("pwd123") },
        { name: "Maria", email: "maria@locataria.com", password: to_md5("pwd123") },
        { name: "Umbrella", email: "joao@anunciante.com", password: to_md5("pwd123") },
      ]
  
      MongoDB.new.drop_danger
      MongoDB.new.insert_users(users)

      sh "cucumber -p jenkins"
end

task :hmg_seeds do

    CONFIG = YAML.load_file(File.join(Dir.pwd, "features/support/config/hmg.yml"))

    users = [
        { name: "Virtrus", email: "virtrudes@cats.com", password: to_md5("pwd123") },
        { name: "Venus", email: "venus@cats.com", password: to_md5("pwd123") },
      ]
  
      MongoDB.new.drop_danger
      MongoDB.new.insert_users(users)
end