pipeline {
    agent {
        docker {
            image 'ruby'
            args '--network host'
        }
    }

    stages {
        stage('Prep') {
            steps {
                sh 'cd rocklov/api && bundle install'
            }
        }

        stage('Testing') {
            steps {
                sh 'cd rocklov/api && rspec'
                junit 'rocklov/api/logs/report.xml'
            }
        }
        
    }
}
